dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  speech_to_text: ^6.6.0
  text_to_speech: ^3.2.1
  flutter_tts: ^3.8.3
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.10
  animated_text_kit: ^4.2.2
  charts_flutter: ^0.12.0
  image_picker: ^1.0.4  # ⬅️ NOVA LINHA ADICIONADA
